-- Snapshot of the production Neon database schema.
-- This is documentation, not a migration runner: nothing in this repo applies
-- this file automatically. It exists so the DB shape is versioned somewhere
-- readable instead of living only inside the Neon console.
--
-- Generated by introspecting the live database (information_schema + pg_catalog).
-- If you change the schema (directly in the Neon console, or via a one-off
-- script), regenerate this file so it doesn't drift — see
-- .claude/database-guidelines.md for how.

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  avatar_color TEXT NOT NULL DEFAULT 'pink',
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  theme TEXT NOT NULL DEFAULT 'dark'
  -- role is app-validated as 'admin' | 'user' (src/lib/db.ts Role type) — no DB check constraint today.
  -- theme is app-validated as 'dark' | 'pink' (src/lib/db.ts Theme type) — no DB check constraint today.
);

CREATE TABLE cards (
  id SERIAL PRIMARY KEY,
  level TEXT NOT NULL,
  question TEXT NOT NULL,
  position INTEGER NOT NULL,
  user_id INTEGER REFERENCES users(id),
  answered_at TIMESTAMPTZ,
  times_completed INTEGER NOT NULL DEFAULT 0
  -- level is app-validated against src/data/cards.ts ALL_LEVELS — no DB check constraint today.
  -- answered_at: NULL = not answered yet; shared across both users (the deck is a joint
  -- reading guide for a call, not per-user progress). Set via an explicit {answered: bool}
  -- request (never a server-side toggle) so two people marking it around the same time
  -- can't race each other into flipping it back off — see src/app/api/cards/[id]/answered.
  -- Only ever meaningful for level='dare' rows: dares never get answered_at set (they never
  -- leave the draw pool), and instead track completions via times_completed, incremented by
  -- src/app/api/cards/[id]/complete.
);

CREATE INDEX cards_user_id_idx ON cards(user_id);

-- Single shared row: the live countdown shown to both signed-in users (e.g. "next time
-- we see each other"). Pinned to id=1 by the check constraint so writes are a plain
-- upsert (INSERT ... ON CONFLICT (id) DO UPDATE) instead of a select-then-branch.
--
-- target_at is the absolute UTC instant — always what the countdown math compares
-- "now" against. time_zone is the IANA zone the date/time was entered in (e.g. the
-- meeting place's zone), used to convert the picked wall-clock time to target_at
-- (see src/lib/countdown.ts zonedTimeToUtc) and to re-populate the edit form correctly.
-- location is a free-text label only (e.g. "Lisbon, Portugal") — never used in the math.
-- Questions generated on-demand by an LLM (via the Vercel AI Gateway) when the manual
-- deck runs dry, or manually from the Manage screen's "AI" tab. Kept separate from
-- `cards` because it has no `position` (no manual ordering — it's drawn like the rest
-- of the deck) and no `user_id` (nobody "owns" an AI-generated question), and because it
-- carries its own metadata (`model`) that has no meaning for a manually-written card.
-- Joined into the shared game pool by src/lib/db.ts getAllCards(), with ids prefixed
-- `ai-<id>` there to disambiguate from `cards` ids.
CREATE TABLE ai_cards (
  id SERIAL PRIMARY KEY,
  level TEXT NOT NULL,
  question TEXT NOT NULL,
  model TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  answered_at TIMESTAMPTZ,
  times_completed INTEGER NOT NULL DEFAULT 0
);

-- Single shared row (singleton, same pattern as `countdown` below): a compact,
-- LLM-maintained summary of topics already covered by answered questions, sent as
-- prompt context instead of the full question history so the prompt stays small as
-- the deck grows. Refreshed periodically by src/lib/ai/context.ts.
CREATE TABLE ai_context (
  id INTEGER PRIMARY KEY DEFAULT 1,
  summary TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ai_context_singleton CHECK (id = 1)
);

CREATE TABLE countdown (
  id INTEGER PRIMARY KEY DEFAULT 1,
  target_at TIMESTAMPTZ NOT NULL,
  time_zone TEXT NOT NULL,
  location TEXT,
  label TEXT NOT NULL DEFAULT 'Together again in',
  CONSTRAINT countdown_singleton CHECK (id = 1)
);
