-- Snapshot of the production Neon database schema.
-- This is documentation, not a migration runner: nothing in this repo applies
-- this file automatically. It exists so the DB shape is versioned somewhere
-- readable instead of living only inside the Neon console.
--
-- Generated by introspecting the live database (information_schema + pg_catalog).
-- If you change the schema (directly in the Neon console, or via a one-off
-- script), regenerate this file so it doesn't drift — see
-- .claude/database-guidelines.md for how.

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  avatar_color TEXT NOT NULL DEFAULT 'pink',
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ
  -- role is app-validated as 'admin' | 'user' (src/lib/db.ts Role type) — no DB check constraint today.
);

CREATE TABLE cards (
  id SERIAL PRIMARY KEY,
  level TEXT NOT NULL,
  question TEXT NOT NULL,
  position INTEGER NOT NULL,
  user_id INTEGER REFERENCES users(id)
  -- level is app-validated against src/data/cards.ts ALL_LEVELS — no DB check constraint today.
  -- user_id has no index today; getCardsForUser() filters by it on every dashboard load —
  -- worth an index (CREATE INDEX cards_user_id_idx ON cards(user_id);) if the deck grows a lot.
);
